### ISSUE TITLE
where is models/model.h5

### ISSUE THREAD

**Issue by SeekPoint** [vendi12/TF_MemN2N-tableQA#1]
ali-186590cc37a5:preprocess yike.ke$ python train.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 219, in <module>
    check_model()
  File "train.py", line 187, in check_model
    model = load_model(path)
  File "/Library/Python/2.7/site-packages/keras/models.py", line 233, in load_model
    f = h5py.File(filepath, mode='r')
  File "/Library/Python/2.7/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/Library/Python/2.7/site-packages/h5py/_hl/files.py", line 101, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-wdzlRM-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-wdzlRM-build/h5py/_objects.c:2798)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-wdzlRM-build/h5py/h5f.c:2117)
IOError: Unable to open file (Unable to open file: name = './models/model.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
ali-186590cc37a5:preprocess yike.ke$

**Comment by svakulenk0** [comment]
work in progress :)

**Comment by SeekPoint** [comment]
great job, expecting...

**Comment by svakulenk0** [comment]
thanks! you can check out the one that works so far demo: https://svakulenko.ai.wu.ac.at/tableqa code: https://github.com/vendi12/MemN2N-tableQA
